repos:
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.8.4
  #   hooks:
  #     - id: ruff
  #       args: [--fix]
  #     - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
    -   id: check-toml
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: check-shebang-scripts-are-executable
